name: Lint

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: khulnasoft/codetypo-action@main
        with:
          incremental_files_only: false
          check_dot_files: true
